all: MikroTik_scp_get MikroTik_scp_send test

MikroTik_scp_get: MikroTik_scp_get.c
	gcc MikroTik_scp_get.c -o MikroTik_scp_get.out

MikroTik_scp_send: MikroTik_scp_send.c
	gcc MikroTik_scp_send.c -o MikroTik_scp_send.out