all: Cisco_telnet_get Cisco_telnet_send

Cisco_telnet_get: Cisco_telnet_get.c
	gcc Cisco_telnet_get.c -o Cisco_telnet_get.out
	
Cisco_telnet_send: Cisco_telnet_send.c
	gcc Cisco_telnet_send.c -o Cisco_telnet_send.out